# coding=utf-8
weather_msg = {'str_template': 'It’s {} today',
               'rainy_sample': '',
               'windy_sample': '',
               'sunny_sample': '',
               'sequence_num': 0}

stat_msgs = [{'str_template': '{} kids under five live along the way',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 1},
             {'str_template': '{} children aged 5-10 live around here',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 2},
             {'str_template': '{} people over 75 live this way',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 3},
             {'str_template': '{} of road fatalities',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 4},
             {'str_template': '{} of serious injuries',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 5},
             {'str_template': '{} of injuries',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 6},
             {'str_template': '{} of crashes',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 7},
             {'str_template': '{} of collisions with trams',
              'high_sample': '',
              'low_sample': '',
              'threshold': 0.5,
              'sequence_num': 8}
             ]
